#!/usr/bin/env bash
# REQ-015 live E2E: cross-service per-test coverage merge on the legacy-tram Brave stack.
#
# Services: order-web(:58080) → reservation → (Tram/Kafka/CDC) → ledger
# Propagation: B3 (Brave / Spring Cloud Sleuth)
# Proven: 2026-06-20, classCount order-web=6, reservation=6, ledger=2
#
# Usage:
#   LEGACY_TRAM_ROOT=/path/to/legacy-tram \
#   bash agent/e2e/legacy-tram-distributed-coverage.sh
#
# Requirements (host):
#   - Docker running and reachable (`docker info` exit 0)
#   - LEGACY_TRAM_ROOT directory present with docker-compose.yml + docker-compose.e2e.yml
#   - Built agent jar (runs ./gradlew :agent:shadowJar if absent)
#   - curl, java on PATH

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LEGACY_TRAM_ROOT="${LEGACY_TRAM_ROOT:-${HOME}/github_graph-rag-test-generator/graph-rag/samples/legacy-tram}"
AGENT_JAR="${REPO_ROOT}/agent/build/libs/jacocoagent-parallel.jar"

FIXED_TRACE_ID="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
FIXED_SPAN_ID="bbbbbbbbbbbbbbbb"
ORDER_URL="http://localhost:58080/orders"

# Temporary working dirs (cleaned up by trap)
COV_ROOT=""
OVERLAY_FILE=""
MAP_FILE=""
OUT_DIR=""

# ---------------------------------------------------------------------------
# Cleanup trap — always teardown Docker stack and temp files
# ---------------------------------------------------------------------------
cleanup() {
    local exit_code=$?
    echo "[e2e] cleanup: tearing down Docker stack..."
    if [[ -n "${OVERLAY_FILE:-}" && -f "${OVERLAY_FILE}" ]]; then
        docker compose \
            -f "${LEGACY_TRAM_ROOT}/docker-compose.yml" \
            -f "${LEGACY_TRAM_ROOT}/docker-compose.e2e.yml" \
            -f "${OVERLAY_FILE}" \
            down -v 2>/dev/null || true
        rm -f "${OVERLAY_FILE}"
    fi
    if [[ -n "${COV_ROOT:-}" && -d "${COV_ROOT}" ]]; then
        rm -rf "${COV_ROOT}"
    fi
    if [[ -n "${MAP_FILE:-}" && -f "${MAP_FILE}" ]]; then
        rm -f "${MAP_FILE}"
    fi
    if [[ -n "${OUT_DIR:-}" && -d "${OUT_DIR}" ]]; then
        rm -rf "${OUT_DIR}"
    fi
    exit "${exit_code}"
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if ! docker info >/dev/null 2>&1; then
    echo "[e2e] SKIP: Docker is not reachable — skipping REQ-015 live E2E."
    exit 0
fi

if [[ ! -d "${LEGACY_TRAM_ROOT}" ]]; then
    echo "[e2e] SKIP: LEGACY_TRAM_ROOT not found: ${LEGACY_TRAM_ROOT} — skipping REQ-015 live E2E."
    exit 0
fi

if [[ ! -f "${LEGACY_TRAM_ROOT}/docker-compose.yml" ]]; then
    echo "[e2e] SKIP: ${LEGACY_TRAM_ROOT}/docker-compose.yml not found — skipping."
    exit 0
fi

# ---------------------------------------------------------------------------
# Step 1 — Build agent shadowJar if needed
# ---------------------------------------------------------------------------
if [[ ! -f "${AGENT_JAR}" ]]; then
    echo "[e2e] Building agent shadowJar..."
    (cd "${REPO_ROOT}" && ./gradlew :agent:shadowJar -q)
fi
echo "[e2e] Agent jar: ${AGENT_JAR}"

# ---------------------------------------------------------------------------
# Step 2 — Coverage directories
# ---------------------------------------------------------------------------
COV_ROOT="$(mktemp -d)/coverage"
mkdir -p "${COV_ROOT}/order-web" "${COV_ROOT}/reservation" "${COV_ROOT}/ledger"
echo "[e2e] Coverage root: ${COV_ROOT}"

# ---------------------------------------------------------------------------
# Step 3 — Generate docker-compose overlay inline
# ---------------------------------------------------------------------------
OVERLAY_FILE="${LEGACY_TRAM_ROOT}/docker-compose.pjacoco-distributed.yml"
cat > "${OVERLAY_FILE}" <<OVERLAY
# Auto-generated by legacy-tram-distributed-coverage.sh — do NOT commit
# Instruments order-web, reservation, ledger with pjacoco agent (B3/Brave).
version: '3.8'
services:
  order-web:
    volumes:
      - ${AGENT_JAR}:/agent/pjacoco.jar:ro
      - ${COV_ROOT}/order-web:/coverage
    environment:
      JAVA_TOOL_OPTIONS: >-
        -javaagent:/agent/pjacoco.jar=destfile=/coverage,includes=sample.order.*,traceKeyAutoCreate=true,traceIdleFlushMillis=5000,traceReaperIntervalMillis=2000,traceLateWriteGraceMillis=2000,maxstores=5000

  reservation:
    volumes:
      - ${AGENT_JAR}:/agent/pjacoco.jar:ro
      - ${COV_ROOT}/reservation:/coverage
    environment:
      JAVA_TOOL_OPTIONS: >-
        -javaagent:/agent/pjacoco.jar=destfile=/coverage,includes=sample.reservation.*,traceKeyAutoCreate=true,traceIdleFlushMillis=5000,traceReaperIntervalMillis=2000,traceLateWriteGraceMillis=2000,maxstores=5000

  ledger:
    volumes:
      - ${AGENT_JAR}:/agent/pjacoco.jar:ro
      - ${COV_ROOT}/ledger:/coverage
    environment:
      JAVA_TOOL_OPTIONS: >-
        -javaagent:/agent/pjacoco.jar=destfile=/coverage,includes=sample.ledger.*,traceKeyAutoCreate=true,traceIdleFlushMillis=5000,traceReaperIntervalMillis=2000,traceLateWriteGraceMillis=2000,maxstores=5000
OVERLAY
echo "[e2e] Overlay written: ${OVERLAY_FILE}"

# ---------------------------------------------------------------------------
# Step 4 — Start stack (zookeeper, kafka, mysql, eventuate-cdc-service, services)
# ---------------------------------------------------------------------------
echo "[e2e] Starting legacy-tram stack..."
docker compose \
    -f "${LEGACY_TRAM_ROOT}/docker-compose.yml" \
    -f "${LEGACY_TRAM_ROOT}/docker-compose.e2e.yml" \
    -f "${OVERLAY_FILE}" \
    up -d --build --wait \
    zookeeper kafka mysql eventuate-cdc-service order-web reservation ledger
echo "[e2e] Stack up."

# ---------------------------------------------------------------------------
# Step 5 — Fire requests with fixed B3 traceId (2-3 times)
# ---------------------------------------------------------------------------
echo "[e2e] Sending orders with fixed B3 traceId=${FIXED_TRACE_ID}..."
for i in 1 2 3; do
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${ORDER_URL}" \
        -H 'Content-Type: application/json' \
        -H "X-B3-TraceId: ${FIXED_TRACE_ID}" \
        -H "X-B3-SpanId: ${FIXED_SPAN_ID}" \
        -H 'X-B3-Sampled: 1' \
        -d '{"userId":"e2e-user","amount":777}')
    echo "[e2e]   POST #${i} → HTTP ${response}"
    if [[ "${response}" != "202" && "${response}" != "200" ]]; then
        echo "[e2e] ERROR: unexpected HTTP status ${response} on POST #${i}"
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Step 6 — Wait for idle reaper flush + CDC async drain
# ---------------------------------------------------------------------------
echo "[e2e] Waiting 20s for idle-reaper flush and async CDC drain..."
sleep 20
echo "[e2e] Wait complete."

# ---------------------------------------------------------------------------
# Step 7 — Write central trace-map
# ---------------------------------------------------------------------------
MAP_FILE="$(mktemp --suffix=.properties)"
echo "${FIXED_TRACE_ID}=sample.OrderFlowE2E#placesOrderAcrossServices" > "${MAP_FILE}"
echo "[e2e] Trace map: ${MAP_FILE}"

# ---------------------------------------------------------------------------
# Step 8 — Merge with TraceMergeMain
# ---------------------------------------------------------------------------
OUT_DIR="$(mktemp -d)/report"
mkdir -p "${OUT_DIR}"
echo "[e2e] Running TraceMergeMain..."
java -cp "${AGENT_JAR}" io.pjacoco.agent.output.TraceMergeMain \
    --shared "${COV_ROOT}" \
    --map "${MAP_FILE}" \
    --report "${OUT_DIR}" \
    --drain-wait-ms 0
echo "[e2e] Merge complete."

# ---------------------------------------------------------------------------
# Step 9 — Assert (REQ-015 acceptance)
# ---------------------------------------------------------------------------
TEST_ID="sample.OrderFlowE2E#placesOrderAcrossServices"
MIN_BYTES=40
PASS=true

for svc in order-web reservation ledger; do
    exec_file="${OUT_DIR}/${svc}/${TEST_ID}.exec"
    if [[ ! -f "${exec_file}" ]]; then
        echo "[e2e] FAIL: missing ${exec_file}"
        PASS=false
    else
        sz=$(wc -c < "${exec_file}" | tr -d ' ')
        echo "[e2e] ${svc}/${TEST_ID}.exec — ${sz} bytes"
        if [[ "${sz}" -le "${MIN_BYTES}" ]]; then
            echo "[e2e] FAIL: ${svc} exec is empty/trivial (${sz} <= ${MIN_BYTES} bytes)"
            PASS=false
        fi
    fi
done

if [[ "${PASS}" != "true" ]]; then
    echo "[e2e] REQ-015 FAIL — one or more service exec files missing or empty."
    exit 1
fi

# ---------------------------------------------------------------------------
# Print success report
# ---------------------------------------------------------------------------
echo ""
echo "REQ-015 PASS — cross-service per-test coverage merged (Brave/legacy-tram)"
echo "  traceId : ${FIXED_TRACE_ID}"
echo "  testId  : ${TEST_ID}"
echo "  services:"
for svc in order-web reservation ledger; do
    exec_file="${OUT_DIR}/${svc}/${TEST_ID}.exec"
    sz=$(wc -c < "${exec_file}" | tr -d ' ')
    echo "    ${svc}: ${sz} bytes"
done
echo ""
